### PR TITLE
Fixed the readmore functionality

### PR DESCRIPTION
**Pull request by prashantrayamajhi**
If the content's length is more than 100, only then "read more" link will be visible

### CODE REVIEW

**Comment by ChoukseyKhushbu** [comment]
> If the content's length is more than 100, only then "read more" link will be visible

 Please remove the `package-lock.json` from the pushed code 
Add it `.gitignore` and create a PR again.

**Comment by prashantrayamajhi** [comment]
i am not being able to make a pull request, you can manage access for me to make one.

**Comment by ChoukseyKhushbu** [comment]
@prashantrayamajhi I don't know why are you not able to make a PR. I have not applied any restrictions for creating PRs to anyone.

**Comment by prashantrayamajhi** [comment]
my bad, have made a pr now xD

**Pull request closed without merging**
